import { useEffect, useState } from 'react';
import { Modal } from '../Modal';
import { Button } from '../Button';
import { GenLine } from './fields';
import type { AiGenerateResult } from '../../data/aiGenerateClient';

const SOURCE_LABEL: Record<AiGenerateResult['source'], string> = {
  model: 'Generated by Einstein',
  composed: 'Composed from your book',
  unavailable: 'Composed from your book',
};

/**
 * Read-only AI result panel. Runs `generate()` on open and on Regenerate. If it
 * resolves `unavailable`/empty or rejects, shows `fallbackText` under a
 * "Composed from your book" subtitle — the chip always produces a real answer.
 */
export function AiResultModal({
  open,
  onClose,
  title,
  subtitle,
  generate,
  fallbackText,
}: {
  open: boolean;
  onClose: () => void;
  title: string;
  subtitle?: string;
  generate: () => Promise<AiGenerateResult>;
  fallbackText: string;
}) {
  const [busy, setBusy] = useState(false);
  const [text, setText] = useState(fallbackText);
  const [source, setSource] = useState<AiGenerateResult['source']>('composed');
  const [nonce, setNonce] = useState(0);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    setBusy(true);
    setText(fallbackText);
    setSource('composed');
    generate()
      .then(r => {
        if (cancelled) return;
        if (r.source === 'model' && r.text.trim()) {
          setText(r.text.trim());
          setSource('model');
        } else {
          setText(fallbackText);
          setSource(r.source === 'unavailable' ? 'unavailable' : 'composed');
        }
      })
      .catch(() => {
        if (!cancelled) {
          setText(fallbackText);
          setSource('composed');
        }
      })
      .finally(() => {
        if (!cancelled) setBusy(false);
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, nonce]);

  return (
    <Modal
      open={open}
      onClose={onClose}
      tone="ai"
      icon={<span>✦</span>}
      title={title}
      subtitle={subtitle ?? SOURCE_LABEL[source]}
      footer={
        <>
          <span className="flex-1 font-mono text-[10px] tracking-[0.04em] text-faint">{SOURCE_LABEL[source]}</span>
          <Button variant="ghost" onClick={onClose}>Close</Button>
          <Button variant="ai" onClick={() => setNonce(n => n + 1)} disabled={busy}>Regenerate</Button>
        </>
      }
    >
      {busy && <GenLine>Generating…</GenLine>}
      <p className="whitespace-pre-line text-[13.5px] leading-relaxed text-fg">{text}</p>
    </Modal>
  );
}
