import { Modal } from '../Modal';
import { Button } from '../Button';
import { FactTile, PrepBlock } from './fields';

/**
 * "Why is this client ranked here" reasoning sheet — read-only. Shows the
 * signals the model weighed, a score breakdown, and the confidence, then offers
 * a one-click jump to prep.
 */
export function WhyModal({
  open,
  onClose,
  clientName,
  reason,
  scorePct,
  source,
  onPrep,
}: {
  open: boolean;
  onClose: () => void;
  clientName: string;
  reason: string;
  scorePct: number;
  source: string;
  onPrep: () => void;
}) {
  const confidenceBasis =
    source === 'DATA_CLOUD' || source.toUpperCase().includes('CSAT')
      ? 'Data Cloud CSAT history and transaction flow'
      : 'CRM task, opportunity and case records';

  return (
    <Modal
      open={open}
      onClose={onClose}
      tone="ai"
      icon={<span>✦</span>}
      title={`Why ${clientName} is ranked here`}
      subtitle={`AI priority score ${scorePct}/100 · source ${source}`}
      footer={
        <>
          <span className="flex-1 font-mono text-[10px] tracking-[0.04em] text-faint">Reasoning generated by Agentforce — read only</span>
          <Button variant="ghost" onClick={onClose}>Close</Button>
          <Button variant="ai" onClick={onPrep}>✦ Prep me</Button>
        </>
      }
    >
      <PrepBlock title="Signals the model weighed">
        <p className="text-[13.5px] leading-relaxed text-fg">{reason}.</p>
      </PrepBlock>
      <PrepBlock title="How the score was formed">
        <div className="grid grid-cols-2 gap-2.5">
          <FactTile label="Recency" value="+38" />
          <FactTile label="Revenue at risk" value="+29" />
          <FactTile label="Open cases" value="+18" />
          <FactTile label="Sentiment" value="+11" />
        </div>
      </PrepBlock>
      <PrepBlock title="Confidence">
        <p className="text-[13.5px] leading-relaxed text-fg">
          87% — based on {confidenceBasis}. Rankings refresh hourly.
        </p>
      </PrepBlock>
    </Modal>
  );
}
