-- Financial Transactions Generation
-- Database: DATA_JEDAIS.FINS__PUBLIC
-- Table:    ACCOUNT_DAILY_BALANCE
-- Purpose:  Daily balance snapshots rebuilt from FINANCIAL_TRANSACTIONS each run.

CREATE OR REPLACE TABLE DATA_JEDAIS.FINS__PUBLIC.ACCOUNT_DAILY_BALANCE (
    ACCOUNTID VARCHAR(50) NOT NULL,
    BALANCE_DATE DATE NOT NULL,
    OPENING_BALANCE NUMBER(15,2) DEFAULT 0,
    DAILY_CREDITS NUMBER(15,2) DEFAULT 0,
    DAILY_DEBITS NUMBER(15,2) DEFAULT 0,
    CLOSING_BALANCE NUMBER(15,2) DEFAULT 0,
    TRANSACTION_COUNT NUMBER(38,0) DEFAULT 0,
    LAST_UPDATED TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ACCOUNTID, BALANCE_DATE)
) COMMENT = 'Daily balance snapshots for detailed account tracking and historical analysis.';
