-- Financial Transactions Generation
-- Database: DATA_JEDAIS.FINS__PUBLIC
-- Table:    FINANCIAL_TRANSACTIONS
-- Purpose:  Primary output table for all generated bank transactions (debits + credits)

CREATE OR REPLACE TABLE DATA_JEDAIS.FINS__PUBLIC.FINANCIAL_TRANSACTIONS (
    ACCOUNTID VARCHAR(16777216),
    TRANSACTIONID VARCHAR(16777216) NOT NULL,
    POSTINGDATE TIMESTAMP_NTZ(9),
    TRANSACTIONDATE TIMESTAMP_NTZ(9),
    AMOUNT NUMBER(38,2),
    DESCRIPTION VARCHAR(16777216),
    TRANSACTION_CATEGORY VARCHAR(16777216),
    MCC NUMBER(38,0),
    MCC_DESCRIPTION VARCHAR(16777216),
    TRANSACTION_STATUS VARCHAR(16777216),
    CURRENCY VARCHAR(16777216),
    TRANSACTION_TYPE VARCHAR(16777216),
    SOURCE_TRANSACTION_TYPE VARCHAR(16777216),
    DATA_DATE TIMESTAMP_NTZ(9),
    SFACCOUNTID VARCHAR(50),
    CONTACTID VARCHAR(50),
    ACCOUNT_TYPE VARCHAR(20),
    PRIMARY KEY (TRANSACTIONID)
);
