-- Financial Transactions Generation
-- Database: DATA_JEDAIS.FINS__PUBLIC
-- Table:    FINANCIAL_TRANSACTION_ACCOUNTS
-- Purpose:  Active accounts that participate in daily transaction generation

CREATE OR REPLACE TABLE DATA_JEDAIS.FINS__PUBLIC.FINANCIAL_TRANSACTION_ACCOUNTS (
    SFACCOUNTID VARCHAR(50),
    ACCOUNTID VARCHAR(50),
    CONTACTID VARCHAR(50),
    ACCOUNTTYPE VARCHAR(25),
    DIRECT_DEPOSIT_AMOUNT NUMBER(18,2),
    BONUS_AMOUNT NUMBER(18,2),
    ACTIVE BOOLEAN
);
