-- Financial Transactions Generation
-- Database: DATA_JEDAIS.FINS__PUBLIC
-- View:     VW_ACCOUNT_SUMMARY
-- Purpose:  Lifetime summary statistics for all active accounts

CREATE OR REPLACE VIEW DATA_JEDAIS.FINS__PUBLIC.VW_ACCOUNT_SUMMARY (
    ACCOUNTID,
    SFACCOUNTID,
    ACCOUNT_TYPE,
    DIRECT_DEPOSIT_AMOUNT,
    BONUS_AMOUNT,
    ACTIVE,
    MONTHS_ACTIVE,
    LIFETIME_CREDITS,
    LIFETIME_DEBITS,
    CURRENT_BALANCE,
    AVG_UTILIZATION_PCT
) COMMENT = 'Lifetime summary statistics for all active accounts'
AS
SELECT 
    c.ACCOUNTID,
    c.SFACCOUNTID,
    c.ACCOUNT_TYPE,
    c.DIRECT_DEPOSIT_AMOUNT,
    c.BONUS_AMOUNT,
    c.ACTIVE,
    COUNT(DISTINCT CONCAT(b.PERIOD_YEAR, '-', b.PERIOD_MONTH)) AS MONTHS_ACTIVE,
    SUM(b.TOTAL_CREDITS) AS LIFETIME_CREDITS,
    SUM(b.TOTAL_DEBITS) AS LIFETIME_DEBITS,
    SUM(b.NET_BALANCE) AS CURRENT_BALANCE,
    AVG(b.CREDIT_UTILIZATION_PCT) AS AVG_UTILIZATION_PCT
FROM DATA_JEDAIS.FINS__PUBLIC.ACCOUNT_CREDIT_CONFIG c
LEFT JOIN DATA_JEDAIS.FINS__PUBLIC.ACCOUNT_BALANCE_TRACKER b ON c.ACCOUNTID = b.ACCOUNTID
WHERE c.ACTIVE = TRUE
GROUP BY c.ACCOUNTID, c.SFACCOUNTID, c.ACCOUNT_TYPE, c.DIRECT_DEPOSIT_AMOUNT, c.BONUS_AMOUNT, c.ACTIVE;
