-- Financial Transactions Generation
-- Database: DATA_JEDAIS.FINS__PUBLIC
-- View:     VW_CURRENT_MONTH_BALANCES
-- Purpose:  Current month balance status for all active accounts with status flags

CREATE OR REPLACE VIEW DATA_JEDAIS.FINS__PUBLIC.VW_CURRENT_MONTH_BALANCES (
    ACCOUNTID,
    PERIOD_YEAR,
    PERIOD_MONTH,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    OPENING_BALANCE,
    TOTAL_CREDITS,
    TOTAL_DEBITS,
    NET_BALANCE,
    AVAILABLE_CREDIT,
    CREDIT_UTILIZATION_PCT,
    TRANSACTION_COUNT,
    LAST_TRANSACTION_DATE,
    LAST_UPDATED,
    ACCOUNT_TYPE,
    DIRECT_DEPOSIT_AMOUNT,
    BONUS_AMOUNT,
    ACCOUNT_STATUS
) COMMENT = 'Current month balance status for all active accounts with account status flags'
AS
SELECT 
    b.*,
    c.ACCOUNT_TYPE,
    c.DIRECT_DEPOSIT_AMOUNT,
    c.BONUS_AMOUNT,
    CASE 
        WHEN b.NET_BALANCE < 0 THEN 'OVERDRAWN'
        WHEN b.CREDIT_UTILIZATION_PCT > 90 THEN 'HIGH_UTILIZATION'
        WHEN b.CREDIT_UTILIZATION_PCT > 70 THEN 'MODERATE_UTILIZATION'
        ELSE 'GOOD_STANDING'
    END AS ACCOUNT_STATUS
FROM DATA_JEDAIS.FINS__PUBLIC.ACCOUNT_BALANCE_TRACKER b
JOIN DATA_JEDAIS.FINS__PUBLIC.ACCOUNT_CREDIT_CONFIG c ON b.ACCOUNTID = c.ACCOUNTID
WHERE b.PERIOD_YEAR = YEAR(CURRENT_DATE())
  AND b.PERIOD_MONTH = MONTH(CURRENT_DATE())
  AND c.ACTIVE = TRUE;
