-- Financial Transactions Generation
-- Database: DATA_JEDAIS.FINS__PUBLIC
-- Task:     DAILY_TRANSACTION_GENERATOR
-- Schedule: 3:05 AM ET daily
-- Purpose:  Generate synthetic bank transactions for all active accounts

CREATE OR REPLACE TASK DATA_JEDAIS.FINS__PUBLIC.DAILY_TRANSACTION_GENERATOR
    WAREHOUSE = TASK_WH
    SCHEDULE = 'USING CRON 5 3 * * * America/New_York'
    STATEMENT_TIMEOUT_IN_SECONDS = 300
    SUSPEND_TASK_AFTER_NUM_FAILURES = 0
    TASK_AUTO_RETRY_ATTEMPTS = 2
    COMMENT = 'Generate transactions for all active accounts from FINANCIAL_TRANSACTION_ACCOUNTS table'
AS
    CALL DATA_JEDAIS.FINS__PUBLIC.SP_RETRY_WRAPPER('DATA_JEDAIS.FINS__PUBLIC.GENERATE_DAILY_TRANSACTIONS(10)', 2);

-- After creating, resume the task:
-- ALTER TASK DATA_JEDAIS.FINS__PUBLIC.DAILY_TRANSACTION_GENERATOR RESUME;
